#!/bin/fish

for f in learn dec101 dec102
    echo marp --html $f.md -o ../docs/prog-lang/decorators/$f.html
    marp --html $f.md -o ../docs/prog-lang/decorators/$f.html
    end
    
tar vzcf dec.tar.gz build learn.md dec101.md dec102.md
