#!/bin/fish

for f in learn dec101 dec102 dec103
    echo marp --html $f.md -o ../docs/prog-lang/decorators/$f.html
    marp --html $f.md -o ../docs/prog-lang/decorators/$f.html

    if test -e $f.puml
        echo plantuml -tpng $f.puml
        plantuml -tpng $f.puml
    end
end

tar vzcf dec.tar.gz build *.md *.puml *.png
