#!/bin/fish

rm *~

echo ""

echo "Generate MARP files...."
for f in looping
    echo marp --html $f.md -o ../docs/prog-lang/looping/$f.html
    marp --html $f.md -o ../docs/prog-lang/looping/$f.html
end
echo ""

echo "Moving PNGs...."
cp -v *.png ../docs/prog-lang/looping/
echo ""

echo "Moving PDFs...."
cp -v *.pdf ../docs/prog-lang/looping/
echo ""

echo "tar up files...."
tar vzcf looping.tar.gz build *.md *.png *.pdf
