#!/bin/fish

rm *~

echo ""

echo "Generate MARP files...."
for f in ml101
    echo marp --html $f.md -o ../docs/ds/ml/$f.html
    marp --html --allow-local-files $f.md -o $f.pdf
    gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=$f-shrunk.pdf $f.pdf
    eza -l $f*.pdf
    mv $f-shrunk.pdf $f.pdf
    marp --html $f.md -o ../docs/ds/ml/$f.html
end
echo ""

echo "Moving PNGs...."
cp -v *.png ../docs/ds/ml/
echo ""

echo "Moving PDFs...."
cp -v *.pdf ../docs/ds/ml/
echo ""

echo "Moving other files...."
cp -v *.csv ../docs/ds/ml/
cp -v *.py ../docs/ds/ml/
echo ""

echo "tar up files...."
tar vzcf ml.tar.gz build *.md *.png viz.py *.csv
