#!/bin/fish

rm *~

echo ""

echo "Generate MARP files...."
for f in ml101
    echo marp --html $f.md -o ../docs/ds/ml/$f.html
    marp --html $f.md -o ../docs/ds/ml/$f.html
end
echo ""

echo "Moving PNGs...."
cp -v *.png ../docs/ds/ml/
echo ""

echo "Moving PDFs...."
cp -v *.pdf ../docs/ds/ml/
echo ""

echo "tar up files...."
tar vzcf ml.tar.gz build *.md *.png
